### PR TITLE
proj_trans_bounds(): sample points within the source grid to avoid missing extent such as world-wide coverage from EPSG:4326 to ESRI:54099 (Spilhaus)

### LINKED ISSUE #61318: Spilhaus not displayed complete in QGIS 3.42.1
### What is the bug or the crash?

Showing a world map (originally  in EPSG:4326) with the Spilhaus projection (i.e. ESRI:54099) does not display the whole map.

Image

If I also plot a vector file with parallels and meridians, those lines cover the full earth.

Image

However, using gdalwarp produces the full map properly
`gdalwarp world.tif spihaus.tif -co COMPRESS=JPEG -t_srs ESRI:54099`

During the development of that projection https://github.com/OSGeo/PROJ/pull/4401 I was able to see the full map properly with an older version of QGIS and the development version of PROJ

Image

This is the QGIS I used during the development. For the projection I used `+proj=spilhaus`:
<table width='100%' align='center'><tr><td>QGIS version</td><td>3.40.0-Bratislava</td></tr><tr><td>QGIS code branch</td><td><a href="https://github.com/qgis/QGIS/tree/release-3_40">Release 3.40</a></td></tr><tr><td colspan="2">&nbsp;</td></tr><tr><td colspan="2"><b>Libraries</b></td></tr><tr><td>Qt version</td><td>5.15.8</td></tr><tr><td>Python version</td><td>3.12.7 (Compiled)<br/>3.12.3 (Running)</td></tr><tr><td>GDAL/OGR version</td><td>3.9.2</td></tr><tr><td>PROJ version</td><td>9.5.0 (Compiled)<br/>9.6.0 (Running)</td></tr><tr><td>EPSG Registry database version</td><td> ()</td></tr><tr><td>GEOS version</td><td>3.13.0-CAPI-1.19.0</td></tr><tr><td>SQLite version</td><td>3.47.0</td></tr><tr><td>PDAL version</td><td>2.8.0</td></tr><tr><td>PostgreSQL client version</td><td>unknown</td></tr><tr><td>SpatiaLite version</td><td>5.1.0</td></td></tr><tr><td>QWT version</td><td>6.3.0</td></tr><tr><td>QScintilla2 version</td><td>2.14.1</td></tr><tr><td>OS version</td><td>Ubuntu 22.04.5 LTS</td></tr><tr><td colspan="2">&nbsp;</td></tr><tr><td colspan="2"><b>Active Python plugins</b></td></tr><tr><td>qgis_points2one</td><td>0.4.0</td></tr><tr><td>reloader</td><td>0.2</td></tr><tr><td>qgis_hub_plugin</td><td>0.3.0</td></tr><tr><td>quick_map_services</td><td>0.21.2</td></tr><tr><td>FreehandRasterGeoreferencer</td><td>0.8.3</td></tr><tr><td>tiss</td><td>2.0.2</td></tr><tr><td>proj_factors_redux</td><td>0.9.1</td></tr><tr><td>valuetool</td><td>3.0.19</td></tr><tr><td>qgis2web</td><td>3.25.1</td></tr><tr><td>db_manager</td><td>0.1.20</td></tr><tr><td>processing</td><td>2.12.99</td></tr><tr><td>grassprovider</td><td>2.12.99</td></tr><tr><td>MetaSearch</td><td>0.3.6</td></tr></table>

### Steps to reproduce the issue

Open a GeoTIFF of the world in EPSG:4326, and change the CRS to ESRI:54099 or a user CRS using `+proj=spilhaus`. Spilhaus only works since PROJ 9.6.0.

Using the QGIS described in the section below, the full map is not plotted. I see only from Antarctica up and right, missing left and bottom parts.

cc @rouault 

### Versions

Installed via conda with
`conda install -c conda-forge gdal qgis proj=9.6.0 pyproj`

<table width='100%' align='center'><tr><td>QGIS version</td><td>3.42.1-Münster</td></tr><tr><td>QGIS code branch</td><td><a href="https://github.com/qgis/QGIS/tree/release-3_42">Release 3.42</a></td></tr><tr><td colspan="2">&nbsp;</td></tr><tr><td colspan="2"><b>Libraries</b></td></tr><tr><td>Qt version</td><td>5.15.15</td></tr><tr><td>Python version</td><td>3.12.9</td></tr><tr><td>GDAL version</td><td>3.10.2</td></tr><tr><td>PROJ version</td><td>9.6.0</td></tr><tr><td>EPSG Registry database version</td><td>v12.004 (2025-03-02)</td></tr><tr><td>GEOS version</td><td>3.13.1-CAPI-1.19.2</td></tr><tr><td>SQLite version</td><td>3.49.1</td></tr><tr><td>PDAL version</td><td>2.8.4</td></tr><tr><td>PostgreSQL client version</td><td>17.4</td></tr><tr><td>SpatiaLite version</td><td>5.1.0</td></td></tr><tr><td>QWT version</td><td>6.3.0</td></tr><tr><td>QScintilla2 version</td><td>2.14.1</td></tr><tr><td>OS version</td><td>Ubuntu 22.04.5 LTS</td></tr><tr><td colspan="2">&nbsp;</td></tr><tr><td colspan="2"><b>Active Python plugins</b></td></tr><tr><td>qgis_points2one</td><td>0.4.0</td></tr><tr><td>reloader</td><td>0.2</td></tr><tr><td>qgis_hub_plugin</td><td>0.3.0</td></tr><tr><td>FreehandRasterGeoreferencer</td><td>0.8.3</td></tr><tr><td>tiss</td><td>2.0.2</td></tr><tr><td>proj_factors_redux</td><td>0.9.1</td></tr><tr><td>valuetool</td><td>3.0.19</td></tr><tr><td>qgis2web</td><td>3.25.1</td></tr><tr><td>db_manager</td><td>0.1.20</td></tr><tr><td>processing</td><td>2.12.99</td></tr><tr><td>grassprovider</td><td>2.12.99</td></tr><tr><td>MetaSearch</td><td>0.3.6</td></tr><tr><td>quick_map_services</td><td>0.21.2</td></tr></table>

### Supported QGIS version

- [x] I'm running a supported QGIS version according to [the roadmap](https://www.qgis.org/en/site/getinvolved/development/roadmap.html#release-schedule).

### New profile

- [ ] I tried with a new [QGIS profile](https://docs.qgis.org/latest/en/docs/user_manual/introduction/qgis_configuration.html#working-with-user-profiles)

### Additional context

Zooming to the left border, it seems to be the Greenwich meridian at the north pole:

Image

The bottom right corner seems to be near the antimeridian.

### PR DESCRIPTION
**Pull request by rouault**
Relates/fixes https://github.com/qgis/QGIS/issues/61318

### CODE REVIEW

File: src/trans_bounds.cpp [hunk 1]
```diff
@@ -501,39 +502,64 @@ int proj_trans_bounds(PJ_CONTEXT *context, PJ *P, PJ_DIRECTION direction,
                        boundary_len, y_boundary_array.data(), sizeof(double),
                        boundary_len, nullptr, 0, 0, nullptr, 0, 0);
 
-    if (output_lon_lat_order) {
+    if (degree_output && !output_lon_lat_order) {
         // Use GIS frienly order
```
Comment (nyalldawson) [inline src/trans_bounds.cpp]:
```suggestion
        // Use GIS friendly order
```

File: src/trans_bounds.cpp [hunk 2]
```diff
@@ -832,11 +858,13 @@ int proj_trans_bounds_3D(PJ_CONTEXT *context, PJ *P, PJ_DIRECTION direction,
                                boundary_len, z_boundary_array.data(),
                                sizeof(double), boundary_len, nullptr, 0, 0);
 
-            if (output_lon_lat_order) {
+            if (degree_output && !output_lon_lat_order) {
                 // Use GIS frienly order
```
Comment (nyalldawson) [inline src/trans_bounds.cpp]:
```suggestion
                // Use GIS friendly order
```

**Review by nyalldawson — APPROVED** [review]
