### PR TITLE
bonne: fix inverse map projection computations when lat_1 < 0 (fixes #3848)

### LINKED ISSUE #3848: Custom World Bonne on Southern Hemisphere not working
#### Example of problem
Custom World Bonne on Southern Hemisphere not working

Used wkt (negative Longitude of natural origin):
```
PROJCRS["World_Bonne",
    BASEGEOGCRS["WGS 84",
        DATUM["World Geodetic System 1984",
            ELLIPSOID["WGS 84",6378137,298.257223563,
                LENGTHUNIT["metre",1,
                    ID["EPSG",9001]]]],
        PRIMEM["Greenwich",0,
            ANGLEUNIT["degree",0.0174532925199433],
            ID["EPSG",8901]]],
    CONVERSION["World_Bonne",
        METHOD["Bonne",
            ID["EPSG",9827]],
        PARAMETER["Latitude of natural origin",-60,
            ANGLEUNIT["Degree",0.0174532925199433],
            ID["EPSG",8801]],
        PARAMETER["Longitude of natural origin",0,
            ANGLEUNIT["Degree",0.0174532925199433],
            ID["EPSG",8802]],
        PARAMETER["False easting",0,
            LENGTHUNIT["metre",1],
            ID["EPSG",8806]],
        PARAMETER["False northing",0,
            LENGTHUNIT["metre",1],
            ID["EPSG",8807]]],
    CS[Cartesian,2],
        AXIS["(E)",east,
            ORDER[1],
            LENGTHUNIT["metre",1,
                ID["EPSG",9001]]],
        AXIS["(N)",north,
            ORDER[2],
            LENGTHUNIT["metre",1,
                ID["EPSG",9001]]],
    USAGE[
        SCOPE["Not known."],
        AREA["World."],
        BBOX[-90,-180,90,180]]]
```
C code:
```c
RawByteString srcUtf8 (UTF8Encode (wkt));
srcTmp = proj_create (ProjContext, srcUtf8.c_str());
...
RawByteString tgtUtf8 (UTF8Encode (gcsOfSrc));
tgtTmp = proj_create (ProjContext, tgtUtf8.c_str());
...
const char *const options[] = {"FORCE_OVER=YES", nullptr /* muss mit null terminieren!*/};
ProjTransformer = proj_create_crs_to_crs_from_pj (ProjContext, srcTmp, tgtTmp, nullptr, options);
...
pjPnt = proj_trans (ProjTransformer, PJ_FWD, pjPnt);

```
#### Problem description

Transformer from GCS to CRS works as expected: 10°/-40° -> 850976.57/2163022.81.
Transformer from the above CRS to it's GCS (geo) does not work - throws! 

#### Expected Output
850976.57/2163022.81 (CRS) -> 10°/-40° (GCS)

#### Environment Information
 - PROJ version 9.1.1
 - Operation System Information

#### Installation method
 - C-Api via DLLs

### PR DESCRIPTION
**Pull request by rouault**
The fixes are directly following hints of Snyder's "Map projections: A working manual"

### CODE REVIEW

File: src/projections/bonne.cpp [hunk 1]
```diff
@@ -58,32 +58,43 @@ static PJ_LP bonne_s_inverse(PJ_XY xy, PJ *P) { /* Spheroidal, inverse */
     double rh;
 
     xy.y = Q->cphi1 - xy.y;
-    rh = hypot(xy.x, xy.y);
+    rh = copysign(hypot(xy.x, xy.y), Q->phi1);
```
Comment (mwtoews) [inline src/projections/bonne.cpp]: minor nit is to have some consistency with L86 (and remove L58)
```suggestion
    const double rh = copysign(hypot(xy.x, xy.y), Q->phi1);
```

**Review by mwtoews — APPROVED** [review]
