### PR TITLE
GeographicBoundingBox::create(): accept degenerate bounding box reduced to a point or a line

### LINKED ISSUE #4236: An area of interest representing a point fails the bbox query
From: https://github.com/pyproj4/pyproj/issues/1326

#### Example of problem

Failing command with PROJ 9.2+
```
PROJ_DEBUG=3 cs2cs "WGS 84" "EPSG:32615" --bbox -93.581543,42.032974,-93.581543,42.032974
```
Failing output:
```
...
No operation found matching criteria
Rel. 9.4.1, June 1st, 2024
<cs2cs>: 
cannot initialize transformation
cause: (null)
program abnormally terminated
```
Successful command:
```
PROJ_DEBUG=3 cs2cs "WGS 84" "EPSG:32615" --bbox -93.581543,42.032974,-93.581542999,42.032974001
```

#### Problem description

An area of interest representing a point is failing the query.

#### Expected Output

Point queries work.

#### Environment Information

- PROJ version: 9.1.1 & 9.4.1 tested
- Operation System Information: Linux

#### Installation method

- conda

### PR DESCRIPTION
**Pull request by rouault**
by extending it by the minimal amount to form a non-degenerate one. Also throws when south > north
Fixes #4236

and:
cs2cs and projinfo: emit warning when it looks like longitude and latitudes have been switched in --bbox

### CODE REVIEW

File: src/iso19111/metadata.cpp [hunk 1]
```diff
@@ -238,6 +238,25 @@ GeographicBoundingBoxNNPtr GeographicBoundingBox::create(double west,
         throw InvalidValueTypeException(
             "GeographicBoundingBox::create() does not accept NaN values");
     }
+    if (south > north) {
+        throw InvalidValueTypeException(
+            "GeographicBoundingBox::create() does not accept south > north");
+    }
+    if (west == east && south == north) {
+        // Avoid creating a degenerate bounding box if reduced to a point
+        if (west > 180)
```
Comment (jjimenezshaw) [inline src/iso19111/metadata.cpp]:
```suggestion
        if (west > -180)
```

File: src/iso19111/metadata.cpp [hunk 2]
```diff
@@ -238,6 +238,25 @@ GeographicBoundingBoxNNPtr GeographicBoundingBox::create(double west,
         throw InvalidValueTypeException(
             "GeographicBoundingBox::create() does not accept NaN values");
     }
+    if (south > north) {
+        throw InvalidValueTypeException(
+            "GeographicBoundingBox::create() does not accept south > north");
+    }
+    if (west == east && south == north) {
```
Comment (jjimenezshaw) [inline src/iso19111/metadata.cpp]: diving in two statements 
if (west == east ) ...
if (south == north) ...
it would also support degenerated lines

File: src/iso19111/metadata.cpp (hunk 1 above)
Comment (rouault) [reply src/iso19111/metadata.cpp]: fixed

File: src/iso19111/metadata.cpp (hunk 2 above)
Comment (rouault) [reply src/iso19111/metadata.cpp]: done

**Review by jjimenezshaw — APPROVED** [review]
