### PR TITLE
unitconvert: round to nearest date when converting to yyyymmdd.

### LINKED ISSUE #1483: unitconvert yyyymmdd to decimalyear error
I noticed some unusual results from using `cct` with unitconvert steps. The conversion from yyyymmdd to decimalyear appears to be wrong in some cases.

1990-01-02 becomes 1990-01-01:
```
$ echo "-117.61748591770593, 59.496749040316935, 329.39612, 19900102" | cct -d 14 +proj=pipeline \
>   +step +proj=unitconvert +t_in=yyyymmdd +t_out=decimalyear \
>   +step +proj=unitconvert +t_in=decimalyear +t_out=yyyymmdd
-117.61748591770592  59.49674904031694  329.39612000000000  19900101.0000
```
Converting 1990-01-02 to a decimal years gives 1990.0027. 
```
$ echo "-117.61748591770593, 59.496749040316935, 329.39612, 19900102" | cct -d 14 +proj=pipeline \
>   +step +proj=unitconvert +t_in=yyyymmdd +t_out=decimalyear
-117.61748591770592  59.49674904031694  329.39612000000000     1990.0027
```
I believe the result should be 1990.0041:
```
$ echo "-117.61748591770593, 59.496749040316935, 329.39612, 1990.0041" | cct -d 14 +proj=pipeline \
>   +step +proj=unitconvert +t_in=decimalyear +t_out=yyyymmdd
-117.61748591770592  59.49674904031694  329.39612000000000  19900102.0000
```
Note that using `+inv` _does_ provide the correct result:
```
$ echo "-117.61748591770593, 59.496749040316935, 329.39612, 19900102" | cct -d 14 +proj=pipeline \
>   +step +proj=unitconvert +t_in=yyyymmdd +t_out=decimalyear \
>   +step +inv +proj=unitconvert +t_in=yyyymmdd +t_out=decimalyear
-117.61748591770592  59.49674904031694  329.39612000000000  19900102.0000
```

I am using proj4 v6.1.0 installed via conda:
```
$ conda list proj4
# packages in environment at /home/trst2284/miniconda3/envs/valkyrie:
#
# Name                    Version                   Build  Channel
proj4                     6.1.0                he751ad9_2    conda-forge
```

### PR DESCRIPTION
**Pull request by direvus**
This resolves an issue where converting from a low-precision decimalyear
to yyyymmdd gave a surprising result, due to mjd_to_yyyymmdd() truncating
away the fractional time component.

This commit changes the behaviour of mjd_to_yyyymmdd() to round to the
nearest date, instead of truncating.

Refs #1483

If this PR is accepted, then it supercedes pull #3074.

 - [x] Closes #1483 
 - [x] Tests added
 - [x] Added clear title that can be used to generate release notes
 - [x] Fully documented, including updating `docs/source/*.rst` for new API

### CODE REVIEW

File: src/conversions/unitconvert.cpp [hunk 1]
```diff
@@ -252,21 +252,22 @@ static double yyyymmdd_to_mjd(double yyyymmdd) {
 /***********************************************************************/
 static double mjd_to_yyyymmdd(double mjd) {
 /************************************************************************
-    Date given in YYYY-MM-DD format.
+    Date returned in YYYY-MM-DD format.
 ************************************************************************/
-    double mjd_iter = 14 + 31;
-    int year = 1859, month=0, day=0;
+    unsigned int mjd_iter = 14 + 31;
```
Comment (kbevers) [inline src/conversions/unitconvert.cpp]: Perhaps rename this to `date_iter` instead. It doesn't make much sense now that the `mjd` variable is gone.

**Review by kbevers — CHANGES_REQUESTED** [review]
Minor nitpick, otherwise it looks good to me

File: src/conversions/unitconvert.cpp (hunk 1 above)
Comment (direvus) [reply src/conversions/unitconvert.cpp]: Yep, that's a fair point.  Branch updated.

**Review by kbevers — APPROVED** [review]

**Comment by kbevers** [comment]
@direvus This looks good to me. Thanks for taking the time to sort this out.
