### PR TITLE
Deal with South Orientated TMerc presented as regular TMerc but with Scale_Factor=-1

### LINKED ISSUE #4425: ESRI Transvers Mercator projections with invalid scale factors
PROJ 9.5.1 has 20 ESRI Transvers Mercator projections that error when round tripped. Their identifiers are from [ESRI:102470](https://spatialreference.org/ref/esri/102470/) to [ESRI:102489](https://spatialreference.org/ref/esri/102489/).

While these projections can be converted to [deprecated] PROJ.4 strings, they error when round-tripped:
```bash
$ projinfo -o PROJ "$(projinfo -o PROJ ESRI:102470 | tail -n +2)"
input string: parsing of '+proj=tmerc +lat_0=0 +lon_0=15 +k=-1 +x_0=0 +y_0=0 +a=6378249.145 +rf=293.4663077 +units=m +no_defs +type=crs' failed: Error 1027 (Invalid value for an argument): tmerc: Invalid value for k/k_0: it should be > 0
$ projinfo -o PROJ "$(projinfo -o PROJ ESRI:102489 | tail -n +2)"
input string: parsing of '+proj=tmerc +lat_0=0 +lon_0=33 +k=-1 +x_0=0 +y_0=0 +ellps=WGS84 +towgs84=0,0,0,0,0,0,0 +units=m +no_defs +type=crs' failed: Error 1027 (Invalid value for an argument): tmerc: Invalid value for k/k_0: it should be > 0
```
The main error (from [init.cpp](https://github.com/OSGeo/PROJ/blob/771248c787a4be91b2609d53b61bd77976c01a20/src/init.cpp#L673)) is:
> tmerc: Invalid value for k/k_0: it should be > 0

Indeed, these scale factors are all bogus, `+k=-1`.

But also, this round-tripping exercise somehow "works" for WKT2:2019:
```bash
$ projinfo -o WKT2:2019 "$(projinfo -o WKT2:2019 ESRI:102470 | tail -n +2)" | grep -e "Lat\|Lon\|Scale"
        PARAMETER["Latitude of natural origin",0,
        PARAMETER["Longitude of natural origin",15,
        PARAMETER["Scale factor at natural origin",-1,
```
Why doesn't this raise an exception with scale factor that is not >0?

(And yes, this is a similar report to #4424)

### PR DESCRIPTION
**Pull request by rouault**
such as ESRI:102470

Fixes #4425

### CODE REVIEW

File: src/iso19111/operation/conversion.cpp [hunk 1]
```diff
@@ -3909,7 +3911,29 @@ void Conversion::_exportToPROJString(
...
+                   parameterValueNumeric(
+                       EPSG_CODE_PARAMETER_SCALE_FACTOR_AT_NATURAL_ORIGIN,
+                       common::UnitOfMeasure::SCALE_UNITY) < 0 &&
+                   parameterValueNumeric(EPSG_CODE_PARAMETER_FALSE_EASTING,
+                                         common::UnitOfMeasure::METRE) == 0 &&
+                   parameterValueNumeric(EPSG_NAME_PARAMETER_FALSE_NORTHING,
+                                         common::UnitOfMeasure::METRE) == 0) {
+            // Deal with ESRI:102470 that use Transverse Mercator with k=-1
+            // to indicate a westing-southing coordinate system, by inserting a
+            // +axis=swu and changing k to 1.
```
Comment (jjimenezshaw) [inline src/iso19111/operation/conversion.cpp]: [minor typo] +axis=wsu

Comment (rouault) [reply src/iso19111/operation/conversion.cpp]: thanks, fixed

**Review by jjimenezshaw — APPROVED** [review]
