### PR TITLE
Let gie skip tests when specific errors are returned.

### LINKED ISSUE #774: Allow gie to skip certain failures
Inspired by the discussion in https://github.com/OSGeo/proj.4/issues/769.

When running the test suite from the build systems we can't be sure to have all grids available. At the moment gie will fail if the grids can't be found during initialization of an operation. I propose we change that so gie instead simply skips tests that require grids. One way to do it is to add another token that can be used in gie-files, e.g. `skip_on_error` which would disregard initialization failures that return a given error number. See example below.

From `4D-API_cs2cs-style.gie` I have modifed a test case to include the proposed `skip_on_error`token:

```

-------------------------------------------------------------------------------
operation  proj=latlong geoidgrids=egm96_15.gtx  ellps=GRS80$
-------------------------------------------------------------------------------
tolerance           15 cm      # lax tolerance due to widespread bad egm96 file
skip_on_error       pjd_err_failed_to_load_grid
accept              12.5 55.5   0
expect              12.5 55.5 -36.0213
direction inverse
accept              12.5 55.5 -36.0213
expect              12.5 55.5  0
```

I imagine the output when running the above test without access to the grids to be something like:

```
$ gie 4D-API-cs2cs-style
../../src/gie ../../../test/gie/4D-API_cs2cs-style.gie
-------------------------------------------------------------------------------
Reading file '../../../test/gie/4D-API_cs2cs-style.gie'
-------------------------------------------------------------------------------
total: 3 tests succeeded, 16 tests skipped, 0 tests failed.
-------------------------------------------------------------------------------
```
The return code from gie should be 0 in this case.

With this change to gie we can avoid complicating the autotools and CMake setups and instead take care of the problem in one place.

### PR DESCRIPTION
**Pull request by kbevers**
Closes #774.

Implemented more or less as specified in the above issue. I've chosen to use `ignore` instead of the suggested `skip_on_error` keyword. 

I still need to adjust the test material in `test/gie` and `test/gigs`.

Below is a test file and the returned output when run by gie:

```
<gie>

-------------------------------------------------------------------------------
operation  proj=hgridshift +grids=nzgd2kgrid0005.gsb  ellps=GRS80
-------------------------------------------------------------------------------
tolerance 1 nm
ignore    pjd_err_failed_to_load_grid
accept    173 -45 0 0
roundtrip 100
-------------------------------------------------------------------------------
expect    172.999892181021551 -45.001620431954613  0 0
direction inverse
accept    172.999892181021551 -45.001620431954613  0 0
expect    173 -45 0 0
-------------------------------------------------------------------------------

-------------------------------------------------------------------------------
operation  proj=hgridshift +grids=nzgd2kgrid0003.gsb  ellps=GRS80
-------------------------------------------------------------------------------
tolerance 1 nm
ignore    pjd_err_failed_to_load_grid
accept    173 -45 0 0
roundtrip 100
-------------------------------------------------------------------------------
expect    172.999892181021551 -45.001620431954613  0 0
direction inverse
accept    172.999892181021551 -45.001620431954613  0 0
expect    173 -45 0 0
-------------------------------------------------------------------------------

-------------------------------------------------------------------------------
operation  proj=hgridshift +grids=nzgd2kgrid0004.gsb  ellps=GRS80
-------------------------------------------------------------------------------
tolerance 1 nm
accept    173 -45 0 0
roundtrip 100
-------------------------------------------------------------------------------
expect    172.999892181021551 -45.001620431954613  0 0
direction inverse
accept    172.999892181021551 -45.001620431954613  0 0
expect    173 -45 0 0
-------------------------------------------------------------------------------

</gie>
```

```
λ bin\gie.exe test.gie
-------------------------------------------------------------------------------
Reading file 'test.gie'
-------------------------------------------------------------------------------
proj=hgridshift +grids=nzgd2kgrid0004.gsb ellps=GRS80
-------------------------------------------------------------------------------
Invalid operation definition in line no. 32: failed to load datum shift file
-------------------------------------------------------------------------------
proj=hgridshift +grids=nzgd2kgrid0004.gsb ellps=GRS80
-------------------------------------------------------------------------------
Invalid operation definition in line no. 32: failed to load datum shift file
-------------------------------------------------------------------------------
total:  3 tests succeeded,  3 tests skipped,  3 tests FAILED!
-------------------------------------------------------------------------------
```

### CODE REVIEW

File: src/gie.c [hunk 1]
```diff
@@ -146,7 +146,7 @@ static ffio *ffio_create (const char **tags, size_t n_tags, size_t max_record_si
 
 static const char *gie_tags[] = {
     "<gie>", "operation", "accept", "expect", "roundtrip", "banner", "verbose",
-    "direction", "tolerance", "builtins", "echo", "</gie>"
+    "direction", "tolerance", "skiperror", "builtins", "echo", "</gie>"
```
Comment (busstoptaktik) [inline src/gie.c]: Suggest "ignore" rather than "skiperror": Seems linguistically more in line with "accept" & "expect"
