### PR TITLE
API: add CRS::promoteTo3D(), proj_crs_promote_to_3D() and proj_crs_create_projected_3D_crs_from_2D() (fixes #1587)

### LINKED ISSUE #1587: Transform Z coordinate doesn't works on a lot of canonical Coordinate System
Transform Z coordinate  doesn't works on a lot of canonical Coordinate System  in 

## Steps to reproduce the problem.

transform coordinate  Z doesn't works, for example, on the following CS's:

**sources CS samples:**
The first one is 3D. I am not sure if the second and the third is also 3D.
if not, how can I make them 3D ?

1. 

PROJCS["ENU (-77.410692720411:39.4145340892321)",GEOGCS["WGS 84",DATUM["World Geodetic System 1984",SPHEROID["WGS 84",6378137.0,298.257223563,AUTHORITY["EPSG","7030"]],AUTHORITY["EPSG","6326"]],PRIMEM["Greenwich",0.0,AUTHORITY["EPSG","8901"]],UNIT["degree",0.017453292519943295],AXIS["Geodetic latitude",NORTH],AXIS["Geodetic longitude",EAST],AXIS["Ellipsoidal height",UP],AUTHORITY["EPSG","4979"]],PROJECTION["Orthographic"],PARAMETER["Latitude_Of_Center",39.4145340892321],PARAMETER["Longitude_Of_Center",-77.410692720411],PARAMETER["false_easting",0],PARAMETER["false_northing",0],UNIT["Meter",1]]

2. 
PROJCS["OSGB 1936 / British National Grid",GEOGCS["OSGB 1936",DATUM["OSGB_1936",SPHEROID["Airy 1830",6377563.396,299.3249646,AUTHORITY["EPSG","7001"]],AUTHORITY["EPSG","6277"]],PRIMEM["Greenwich",0,AUTHORITY["EPSG","8901"]],UNIT["degree",0.01745329251994328,AUTHORITY["EPSG","9122"]],AUTHORITY["EPSG","4277"]],UNIT["metre",1,AUTHORITY["EPSG","9001"]],PROJECTION["Transverse_Mercator"],PARAMETER["latitude_of_origin",49],PARAMETER["central_meridian",-2],PARAMETER["scale_factor",0.9996012717],PARAMETER["false_easting",400000],PARAMETER["false_northing",-100000],AUTHORITY["EPSG","27700"],AXIS["Easting",EAST],AXIS["Northing",NORTH]]

3.
PROJCS["Orthographic (-85.4876596902845000,32.6035190542778000)",GEOGCS["GCS_WGS_1984",DATUM["D_unknown",SPHEROID["WGS84",6378137,298.257223563]],PRIMEM["Greenwich",0],UNIT["Degree",0.017453292519943295]],PROJECTION["Orthographic"],PARAMETER["Latitude_Of_Center",32.6035190542778000],PARAMETER["Longitude_Of_Center",-85.4876596902845000],PARAMETER["false_easting",0],PARAMETER["false_northing",0],UNIT["Meter",1]]

**Destination CS:**

COMPD_CS["WGS 84 + EGM96 geoid height",
    GEOGCS["WGS 84",
        DATUM["WGS_1984",
            SPHEROID["WGS 84",6378137,298.257223563,
                AUTHORITY["EPSG","7030"]],
            AUTHORITY["EPSG","6326"]],
        PRIMEM["Greenwich",0,
            AUTHORITY["EPSG","8901"]],
        UNIT["degree",0.0174532925199433,
            AUTHORITY["EPSG","9122"]],
        AXIS["Latitude",NORTH],
        AXIS["Longitude",EAST],
        AUTHORITY["EPSG","4326"]],
    VERT_CS["EGM96 height",
        VERT_DATUM["EGM96 geoid",2005,
            AUTHORITY["EPSG","5171"]],
        UNIT["metre",1,
            AUTHORITY["EPSG","9001"]],
        AXIS["Gravity-related height",UP],
        AUTHORITY["EPSG","5773"]]] 

## Operating system

Windows 10

### PR DESCRIPTION
**Pull request by rouault**
Also add a --3d switch to projinfo

### CODE REVIEW

File: src/iso19111/c_api.cpp [hunk 1]
```diff
@@ -3197,6 +3197,151 @@ PJ *proj_crs_alter_parameters_linear_unit(PJ_CONTEXT *ctx, const PJ *obj,
...
+
+// ---------------------------------------------------------------------------
+
+/** \brief Create a projected 3D CRS from an existing projected 2D CRS.
+ *
+ * The passed projected_2D_crs is used so that its name is replaced by
+ * crs_name and its base geographic CRS is replaced by geog_3D_crs. The vertical
+ * axis of geog_3D_crs (ellipsoidal height) will be added as the 3rd axis of
+ * the resulting projected 3D CRS.
+ * Normally, the passed geog_3D_crs should be the 3D conterpart of the original
```
Comment (kbevers) [inline src/iso19111/c_api.cpp]:
```suggestion
 * Normally, the passed geog_3D_crs should be the 3D counterpart of the original
```

**Review by kbevers — APPROVED** [review]
Looks good to me. I found a typo in a comment, but otherwise okay
