### PR TITLE
Grid correction: fix handling grids spanning antimeridian (fixes #1859)

### LINKED ISSUE #1859: PROJ: height geoid correction:  incorrect transformation for geoid crossing 180|-180 bound
#### Example of problem
Hello, i have next transformation but it doesn't apply geoid height correction after -180|180 bound crossing:

```c
./cs2cs  EPSG:4979  EPSG:8812 <<EOF
53 179 0
53 180 0
53 -180 0
53 -179 0
EOF
664633.91       234200.79 1.03
731629.27       230002.06 -1.62
731629.27       230002.06 0.00
798676.55       226735.53 0.00
```
If i understand correctly, this transformation should be performed using `geoid06_ak.gtx` geoid:
```
/projinfo -s EPSG:4979 -t EPSG:8812 --spatial-test intersects

Candidate operations found: 10
-------------------------------------
Operation n°1:

unknown id, Inverse of NAD83(HARN) to WGS 84 (1) + NAD83(HARN) to NAVD88 height (9) + NAD83(HARN) to W
GS 84 (1) + Inverse of NAD83 to WGS 84 (2) + SPCS83 Alaska zone 10 (meters), 10.02 m, USA - Alaska - A
leutian Islands

PROJ string:
+proj=pipeline +step +proj=axisswap +order=2,1 +step +proj=unitconvert +xy_in=deg +xy_out=rad +step +i
nv +proj=vgridshift +grids=geoid06_ak.gtx +multiplier=1 +step +proj=push +v_3 +step +proj=cart +ellps=
WGS84 +step +inv +proj=helmert +x=-2 +y=0 +z=4 +step +inv +proj=cart +ellps=GRS80 +step +proj=pop +v_3
 +step +proj=lcc +lat_0=51 +lon_0=-176 +lat_1=53.8333333333333 +lat_2=51.8333333333333 +x_0=1000000 +y
_0=0 +ellps=GRS80
...
   USAGE[
        SCOPE["unknown"],
        AREA["USA - Alaska - Aleutian Islands"],
        BBOX[51.3,172.42,54.34,-164.84]]]
```
Bounds are:
```
South lat: 51.300000 deg
West long: 172.420000 deg
East long: -164.840000 deg
North lat: 54.340000 deg
```
Geoid info:
```
./gdalinfo ../share/proj/geoid06_ak.gtx
Driver: GTX/NOAA Vertical Datum .GTX
Files: ../share/proj/geoid06_ak.gtx
Size is 3721, 1381
Coordinate System is:
GEOGCRS["WGS 84",
    DATUM["World Geodetic System 1984",
        ELLIPSOID["WGS 84",6378137,298.257223563,
            LENGTHUNIT["metre",1]]],
    PRIMEM["Greenwich",0,
        ANGLEUNIT["degree",0.0174532925199433]],
    CS[ellipsoidal,2],
        AXIS["geodetic latitude (Lat)",north,
            ORDER[1],
            ANGLEUNIT["degree",0.0174532925199433]],
        AXIS["geodetic longitude (Lon)",east,
            ORDER[2],
            ANGLEUNIT["degree",0.0174532925199433]],
    ID["EPSG",4326]]
Data axis to CRS axis mapping: 2,1
Origin = (171.991666666666674,72.008333333333340)
Pixel Size = (0.016666666666667,-0.016666666666667)
Corner Coordinates:
Upper Left  ( 171.9916667,  72.0083333) (171d59'30.00"E, 72d 0'30.00"N)
Lower Left  ( 171.9916667,  48.9916667) (171d59'30.00"E, 48d59'30.00"N)
Upper Right (     234.008,      72.008) (234d 0'30.00"E, 72d 0'30.00"N)
Lower Right (     234.008,      48.992) (234d 0'30.00"E, 48d59'30.00"N)
Center      (     203.000,      60.500) (203d 0' 0.00"E, 60d30' 0.00"N)
Band 1 Block=3721x1 Type=Float32, ColorInterp=Undefined
  NoData Value=-88.8888000000000034

```
#### Problem description

I suppose it's a bug that geoid correction isn't applied for current transformation. Perhaps this issue related to https://github.com/OSGeo/PROJ/issues/158 

#### Environment Information
 - PROJ version (`proj 6.3.0`)
 - `macOS Catalina 10.15.2`

#### Installation method
 - from source

### PR DESCRIPTION
**Pull request by rouault**

### CODE REVIEW

File: src/grids.cpp [hunk 1]
```diff
@@ -3119,23 +3134,43 @@ static double read_vgrid_value(PJ_CONTEXT *ctx, const ListOfVGrids &grids,
...
+                          grid->width());
+        } else {
+            grid_x = (input.lam - 2 * M_PI - extent.westLon) / extent.resLon;
+        }
     }
     double grid_y = (input.phi - extent.southLat) / extent.resLat;
     int grid_ix = static_cast<int>(lround(floor(grid_x)));
-    assert(grid_ix >= 0 && grid_ix < grid->width());
+    if (!(grid_ix >= 0 && grid_ix < grid->width())) {
+        // Shouldn't happen, but I don't trust asserts
```
Comment (kbevers) [inline src/grids.cpp]: Why not?

Comment (rouault) [reply src/grids.cpp]: > Why not?

Experience :-) Pretty much all assertions become runtime failures if people try to torture the code sufficiently. I suspect here that there could be some floating point issues if trying very close to the grid boundary

Comment (kbevers) [reply src/grids.cpp]: Fair enough :-) Maybe just remove the comment about not trusting asserts. It makes sense in the diff where the context is clear but when reading this in the future I think it will just be a confusing statement. Instead, "in the unlikely case we end up here, ..."

Comment (rouault) [reply src/grids.cpp]: Comment changed as suggested.
