### PR TITLE
Fix segfaults in case of out-of-memory situations

### LINKED ISSUE #1678: potential segfault in out of memory situations
I found two placed that did not handle out-of-memory situations correctly.
Problematic functions:
- pj_datum_set(...) in src/datum_set.cpp
- ellps_ellps(...) in src/ell_set.cpp

I'll provide a pull request for a fix.

### PR DESCRIPTION
**Pull request by yonarw**
This fixes #1678

### CODE REVIEW

File: src/ell_set.cpp [hunk 1]
```diff
@@ -156,7 +157,14 @@ static int ellps_ellps (PJ *P) {
     err = proj_errno_reset (P);
 
     paralist* new_params = pj_mkparam (ellps->major);
+    if (nullptr == new_params)
+        return proj_errno_set (P, ENOMEM);
     new_params->next = pj_mkparam (ellps->ell);
+    if (nullptr == new_params)
```
Comment (rouault) [inline src/ell_set.cpp]: cppcheck complains:
```
/home/travis/build/OSGeo/PROJ/src/ell_set.cpp:163,warning,nullPointer,Possible null pointer dereference: new_params - otherwise it is redundant to check it against null.
```
Indeed the check should be against new_params->next
